#include <string_view>

constexpr std::string_view Igor_ipf{
"#pragma TextEncoding = \"UTF-8\"\r"
"#pragma rtGlobals=3\t\t// Use modern global access method and strict wave access.\r"
"\r"
"Menu \"Macros\"\r"
"\t\"Display Waves\", DisplayWavesByFolder()\r"
"End\r"
"\r"
"Function DisplayAllWavesInFolder(folder)\r"
"DFREF folder\r"
"\tString objName\r"
"\tvariable n_wave=CountObjectsDFR(folder, 1)\r"
"\tif(n_wave>0)\r"
"\t\tDisplay\r"
"\t\tvariable index\r"
"\t\tfor(index = 0; index < n_wave; index+=1)\r"
"\t\t\tobjName = GetIndexedObjNameDFR(folder, 1, index)\r"
"\t\t\tAppendToGraph folder:$objName\r"
"\t\tendfor\r"
"\tendif\r"
"End\r"
"\r"
"function TraversDatafolders(folder)\r"
"DFREF folder\r"
"\tvariable n_subfolders = CountObjectsDFR(folder, 4)\r"
"\tif(n_subfolders>0)\r"
"\t\tvariable i\r"
"\t\tfor(i=0; i < n_subfolders; i+=1)\r"
"\t\t\tstring subfolder = GetIndexedObjNameDFR(folder, 4, i)\r"
"\t\t\tDFREF refsf = folder:$subfolder\r"
"\t\t\tprint subfolder\r"
"\t\t\tTraversDatafolders(refsf)\r"
"\t\tendfor\r"
"\telse\r"
"\t\tDisplayAllWavesInFolder(folder)\r"
"\tendif\r"
"end\r"
"\r"
"function DisplayWavesByFolder()\r"
"\tTraversDataFolders(root:)\r"
"\tExecute \"TileWindows/O=1/C/P\"\r"
"end\r" };
